# Configs/config.yaml
project_name: "Knee-Osteoarthritis-Grading"

data:
  raw_dir: "Data/Raw"
  processed_dir: "Data/Processed"
  batch_size: 32
  img_size: [224, 224]

model:
  name: "ResNet50"
  num_classes: 5
  learning_rate: 0.001
  epochs: 50

paths:
  model_save_dir: "Models/"
  log_dir: "Reports/Logs/"